
spring:
  application:
    name: BackendManager
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: Jmalexis322422

server:
  address: 0.0.0.0
  port: 8088
  error:
    include-exception: true
    include-message: always